import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/banner';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Netflix</h1>

      {/* <NavBar /> */}
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl=""
      />

      {/* <Card /> */}
    </div>
  );
}
